// DataAnnotations = the built-in validation library
// [Required], [Range], [MinLength] all live here
// These run automatically on every POST — you write zero validation code in the controller
using System.ComponentModel.DataAnnotations;

// Our custom attributes — domain rules that built-in annotations can't express
// "Is this a valid transaction type for a hospital?" is business logic, not a generic check
using EHRMvcAuditLedgerDemo.Validation;

namespace EHRMvcAuditLedgerDemo.Models
{
    // This class is THREE things at once:
    // 1. A C# object your controller works with
    // 2. A map to Healthcare.PatientTransactions table in SQL (via EHRDbContext)
    // 3. A validation contract — invalid data never gets past this class
    public class PatientTransaction
    {
        // [Key] tells EF Core "this is the PRIMARY KEY"
        // Value is auto-generated by SQL Server (IDENTITY column) — you never set this manually
        [Key]
        public int TransactionId { get; set; }

        // [Required] catches null and empty string
        // Without this, a blank patient name would save to the DB silently
        // Real hospital: PatientName alone isn't enough — you'd link to a PatientId (FK)
        // so records are tied to a verified patient identity, not a free-text string anyone can type
        [Required(ErrorMessage = "Patient name is required")]
        public string PatientName { get; set; } = string.Empty;

        // [AllowedTransactionType] is our custom rule — only "Billing" or "Pharmacy" allowed
        // Built-in annotations can't do this — they don't know your hospital's transaction types
        // Real hospital: this would be an enum or a FK to a ReferenceData table
        // so adding a new type doesn't require a code change and redeployment
        [Required]
        [AllowedTransactionType]
        public string TransactionType { get; set; } = string.Empty;

        // [Range] blocks zero, negative, and absurdly large amounts
        // A $0 billing entry or a $999,999,999 charge are both data integrity failures
        // Real hospital: upper limit would match your hospital's actual max procedure cost
        // and currency precision matters — decimal(18,2) in SQL, never float (float loses cents)
        [Range(1, 100000, ErrorMessage = "Amount must be realistic")]
        public decimal Amount { get; set; }

        // [MinLength(10)] forces meaningful documentation — "ok" or "done" aren't valid notes
        // Real hospital: clinical descriptions are legally discoverable in malpractice cases
        // A 2-word description that gets required is a liability, not just bad data
        [Required]
        [MinLength(10, ErrorMessage = "Description too short")]
        public string Description { get; set; } = string.Empty;

        // [FutureOrTodayDate] is our custom rule — no backdating transactions
        // Backdating a billing entry is insurance fraud — this attribute is a compliance guard
        // Real hospital: you'd also add [PastDateWithin90Days] for amendment scenarios
        // where corrections to recent records are allowed but ancient backdating is not
        [FutureOrTodayDate]
        public DateTime TransactionDate { get; set; }
    }
}